### PR TITLE
Fix crashes when searching for a facet with all null values

### LINKED ISSUE #279: Searching for a facet with all null values causes a 500 error
For amp_pd there are a few columns for sample metrics that are all null. Searching for these causes this error:

apise_1_5800c725a6d1 |   File "/app/data_explorer/controllers/facets_controller.py", line 72, in facets_get
apise_1_5800c725a6d1 |     _process_extra_facets(extraFacets)
apise_1_5800c725a6d1 |   File "/app/data_explorer/controllers/facets_controller.py", line 48, in _process_extra_facets
apise_1_5800c725a6d1 |     es, elasticsearch_field_name, field_type)
apise_1_5800c725a6d1 |   File "/app/data_explorer/util/elasticsearch_util.py", line 314, in get_elasticsearch_facet
apise_1_5800c725a6d1 |     field_type)
apise_1_5800c725a6d1 |   File "/app/data_explorer/util/elasticsearch_util.py", line 53, in _get_bucket_interval
apise_1_5800c725a6d1 |     field_range = _get_field_range(es, field_name)
apise_1_5800c725a6d1 |   File "/app/data_explorer/util/elasticsearch_util.py", line 49, in _get_field_range
apise_1_5800c725a6d1 |     return (aggs['max']['value'] - aggs['min']['value'])
apise_1_5800c725a6d1 | TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

Lets fix this so that it just displays 0 values instead.

### PR DESCRIPTION
**Pull request by wnojopra**
Fixes #279 
Before:
  Request Errors
After:
  
screenshot from 2019-02-28 10-39-19

### CODE REVIEW

**Comment by melissachang** [comment]
Thanks.

Let's get rid of that horizontal line. In HistogramFacet.js, let's only display the Vega div if values is not empty.

(TextFacet is fine.)

**Comment by wnojopra** [comment]
Got rid of the line for empty values
screenshot from 2019-02-28 14-30-47

File: ui/src/components/facets/HistogramFacet.js [hunk 1]
```diff
@@ -158,6 +160,16 @@ class HistogramFacet extends Component {
...
+      );
+    }
+
+    return (
+      <div className={classes.histogramFacet}>
+        <FacetHeader
+          facet={this.props.facet}
+          selectedValues={this.props.selectedValues}
+        />
+        {vegaDiv}
```
Comment (melissachang) [inline ui/src/components/facets/HistogramFacet.js]: opt

I find [Inline if](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator) easier to read. Then you could keep the vega stuff here. You don't need to change it, just letting you know this is an option for next time.
